/**
 * Tunable constants shared by the Worker and the browser.
 *
 * Anything the UI must agree with the server about lives here, and most of it is
 * also echoed by `GET /api/config` so a deployed client can never disagree with a
 * deployed server.
 */

import type { AmericanPrice, League } from './types.js';

/**
 * Opening balance, deposited once per ACCOUNT in the signup batch (M5b). It is
 * not per league, not per season and never re-granted: there is exactly one
 * `deposit_initial` ledger row per balance, for the life of the account.
 */
export const INITIAL_BANKROLL_CENTS = 100_000;

/** Minimum stake: $1.00. Also enforced by a CHECK constraint on `bets`. */
export const MIN_STAKE_CENTS = 100;

/**
 * Hard cap on any single bet's total return ($1,000,000). Two jobs:
 *   1. A real product rule — every sportsbook caps payouts.
 *   2. It PROVES `bets.potential_payout_cents` / `payout_cents` fit in both an
 *      SQLite INTEGER and a JS `number`: 1e8 vs 2^53 is ~7.95 orders of
 *      magnitude of headroom, so no money column can silently become REAL.
 * A bet above the cap is rejected at placement with PAYOUT_LIMIT_EXCEEDED; the
 * comparison happens in BigInt before any Number conversion.
 *
 * Lives HERE and not in odds.ts because the browser needs it too: the bet slip
 * calls `exceedsPayoutCap()` for pre-flight, and `GET /api/config` echoes it as
 * `maxPayoutCents` so a deployed client cannot disagree with a deployed server.
 * For reference, the largest realistic payout — a 10-leg -110 parlay at the full
 * $1,000 bankroll — returns 64,308,161 cents, comfortably under the cap.
 */
export const MAX_PAYOUT_CENTS = 100_000_000;

/** Parlay leg bounds. A straight bet is exactly 1 leg. */
export const MIN_PARLAY_LEGS = 2;
export const MAX_PARLAY_LEGS = 10;

// ---------------------------------------------------------------------------
// Teasers (M5b). Research and sources: docs/teaser-odds.md, summarised in
// PLAN.md §5.8.
// ---------------------------------------------------------------------------

/**
 * The point tiers we offer, in TENTHS of a point: every whole point from 3 to
 * 14, plus 6.5.
 *
 * Tenths because 6.5 has no integer representation in points, and because every
 * other line quantity in this system is already tenths (PLAN.md §3.1) — mixing
 * units is how a 6.5-point teaser ends up teasing by 6.
 */
export const TEASER_POINTS_TENTHS = [
  30, 40, 50, 60, 65, 70, 80, 90, 100, 110, 120, 130, 140,
] as const;
export type TeaserPointsTenths = (typeof TEASER_POINTS_TENTHS)[number];

/** A teaser is a parlay shape: never fewer than two legs, never more than ten. */
export const MIN_TEASER_LEGS = 2;

/**
 * Books stop posting a MONEYLINE once the spread is this wide: the favourite
 * would pay -20000 and nobody takes it. Measured 2026-09-16 on The Odds API's
 * CFB slate (75 games, nine US books): the 15 games with no moneyline at the
 * five preferred books had none at ANY of the nine, and every one of them had
 * a spread of 33.5 or more; the widest spread that still HAD a DraftKings
 * moneyline was 35.5. At or beyond this line an absent moneyline is book
 * policy, not a gap — the board says "No ML" instead of "n/a", and the planned
 * secondary-provider sweep does not count it as a market worth spending a
 * credit on. Tenths of a point, like every line.
 */
export const MONEYLINE_NOT_OFFERED_SPREAD_TENTHS = 300;

/** Leg counts the card prices. Same ceiling as a parlay. */
export type TeaserLegCount = 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

/**
 * THE TEASER CARD: a FIXED price per (points, legs), in integer American.
 *
 * A teaser is NOT priced as the product of its legs — that is the whole point of
 * the product. Moving every line six points in the bettor's favour destroys the
 * legs' individual prices, so the book posts a flat card instead, and
 * `bet_legs.american_price` for a teaser leg is a placeholder (+100, even money)
 * that carries no pricing meaning. `bets.american_price` is the card value.
 *
 * THIRTEEN TIERS, 3 to 14 points (plus 6.5), every one with full push
 * protection (a push reduces the leg count, PLAN.md §5.8). The 6 / 6.5 / 7 /
 * 8 / 9-point columns are Bovada's published "classic standard" card verbatim —
 * the only fully populated 2-10-leg grid any book prints. The other eight tiers
 * are GENERATED by scripts/teaser-card.mjs from one model fitted to those 45
 * published cells: a teased leg wins with probability Φ(points / 14.65) (normal
 * margin-vs-spread, σ fitted) and the book keeps a flat 3.25% hold, so an
 * n-leg price is (1 − hold) / p^n, rounded as a card is printed. On the two
 * DraftKings "ties lose" specialty tiers it was not fitted to it comes out
 * WORSE for the bettor (our 10-pt 3-leg −150 vs DK −120; 13-pt 4-leg −200 vs
 * DK −140), which is the right side to err on since ours pay pushes. Sourcing and the model are in
 * docs/teaser-odds.md; regenerate with `node scripts/teaser-card.mjs`.
 *
 * Every value round-trips through `americanToPrice`/`priceToAmerican` exactly
 * (a generated cell can never be ±100, which has no American form). The worst
 * cell is the 10-leg 3-point +12500 at the full 100,000¢ bankroll =
 * 12,600,000¢ (script output), an 8× margin under MAX_PAYOUT_CENTS — so
 * `exceedsPayoutCap` stays unreachable for a teaser and is still checked, for
 * free, on the shared path.
 */
export const TEASER_PAYOUTS: Readonly<
  Record<TeaserPointsTenths, Readonly<Record<TeaserLegCount, AmericanPrice>>>
> = {
  30: { 2: 155, 3: 325, 4: 575, 5: 1000, 6: 1700, 7: 2800, 8: 4500, 9: 7500, 10: 12500 },
  40: { 2: 130, 3: 250, 4: 450, 5: 725, 6: 1200, 7: 1900, 8: 2900, 9: 4500, 10: 7000 },
  50: { 2: 105, 3: 200, 4: 350, 5: 550, 6: 825, 7: 1300, 8: 1900, 9: 2800, 10: 4000 },
  60: { 2: -120, 3: 150, 4: 260, 5: 400, 6: 600, 7: 900, 8: 1400, 9: 1900, 10: 2500 },
  65: { 2: -130, 3: 135, 4: 225, 5: 350, 6: 500, 7: 800, 8: 1100, 9: 1500, 10: 2000 },
  70: { 2: -140, 3: 120, 4: 200, 5: 325, 6: 450, 7: 700, 8: 900, 9: 1200, 10: 1500 },
  80: { 2: -165, 3: 105, 4: 155, 5: 225, 6: 300, 7: 425, 8: 600, 9: 750, 10: 1000 },
  90: { 2: -185, 3: -115, 4: 130, 5: 185, 6: 250, 7: 325, 8: 425, 9: 550, 10: 700 },
  100: { 2: -250, 3: -150, 4: -105, 5: 140, 6: 190, 7: 250, 8: 325, 9: 400, 10: 500 },
  110: { 2: -300, 3: -185, 4: -125, 5: 110, 6: 145, 7: 190, 8: 225, 9: 300, 10: 350 },
  120: { 2: -375, 3: -225, 4: -155, 5: -115, 6: 115, 7: 145, 8: 175, 9: 225, 10: 250 },
  130: { 2: -475, 3: -275, 4: -200, 5: -145, 6: -115, 7: 110, 8: 135, 9: 160, 10: 195 },
  140: { 2: -600, 3: -350, 4: -250, 5: -185, 6: -145, 7: -120, 8: 105, 9: 120, 10: 145 },
};

/** True for a value that indexes `TEASER_PAYOUTS`. */
export function isTeaserPoints(value: unknown): value is TeaserPointsTenths {
  return (TEASER_POINTS_TENTHS as readonly unknown[]).includes(value);
}

/**
 * Betting closes this long BEFORE the stored kickoff time. Covers clock skew,
 * Workers' I/O-frozen `Date.now()`, and ESPN kickoff times being approximate.
 * See PLAN.md §14.1.
 */
export const BET_CUTOFF_BUFFER_MS = 60_000;

/**
 * A `game_lines` row whose `seen_at` is older than this is not offered for
 * betting. Measured against `seen_at` (last confirmation), NOT `captured_at`
 * (last price change), so the compare-and-skip upsert can leave an unchanged
 * line alone without making it look stale.
 */
export const LINE_STALE_MS = 3 * 60 * 60 * 1000;

/**
 * The staleness window is `max(LINE_STALE_MS, LINE_STALE_MULTIPLIER × the
 * game's expected refresh cadence)` — see `lineStaleAfterMs` in
 * src/worker/ingest.ts. A game days from kickoff is only refreshed every 6 h
 * (PLAN.md §8.4), so a flat 3 h window declared its line stale for half of
 * every day, for no reason: the window exists to notice a BROKEN ingest, not to
 * police line movement, and this is fake money. Three cycles missed is broken.
 */
export const LINE_STALE_MULTIPLIER = 3;

/**
 * WRITE-BUDGET LEVERS (PLAN.md §8.6). D1 free tier allows 100,000 rows written
 * per UTC day and since 2026-09-01 it is HARD-ENFORCED: past the cap, D1 returns
 * errors, which would block bet placement and settlement, not just staleness.
 *
 * The ingest upsert therefore writes a row only when a value actually changed,
 * or when the "last seen" stamp is older than these touch intervals.
 */
export const GAME_SEEN_TOUCH_MS = 6 * 60 * 60 * 1000;
export const LINE_SEEN_TOUCH_MS = 45 * 60 * 1000;

/**
 * Refresh slot allocation. `REFRESH_TARGETS_PER_RUN` is 2 (env var), and the two
 * slots are NOT interchangeable:
 *   slot 1  the most-due target overall — in practice a live one
 *   slot 2  RESERVED for the most-overdue target with no in-progress game
 *
 * Without the reservation, a Saturday with a live CFB target and a live NFL
 * target would consume both slots on all 96 runs and the other ~20 targets
 * (next week's line discovery) would starve indefinitely; `priority ASC,
 * next_run_at ASC` alone does not prevent that.
 *
 * Budget check (computed, under the §22 Monday window): the window spans 2 ET
 * dates at its narrowest (an NFL Sunday morning), 7 on a Tuesday, 8 on a Monday
 * and at most 9 (a Sunday after the rollover), so at most 9 × 2 leagues = 18
 * targets — 16 on a Monday, 14 from Tuesday on. Worst case 2 are live, leaving
 * 16 discovery targets that each
 * want a +6 h refresh = 4/day = 64 slot-uses/day against a supply of 96 — 32 to
 * spare, where the pre-M9-0 10-day window left 16. If two targets are live at
 * once they alternate in slot 1 and each gets a 30-minute cadence, which
 * settlement tolerates.
 */
export const RESERVED_DISCOVERY_SLOTS = 1;

/**
 * HARD CEILING on how far ahead the ingest planner will ever look. It is NOT
 * the window any more: since M9-0 the board and the planner both end at
 * `boardWindowEnd(league, now)` (src/shared/time.ts, PLAN.md §22), which closes
 * on the Monday that ends the football week and is at most ~9 days wide.
 *
 * So this never binds in normal operation, and that is the point: it is the
 * blast-radius bound on a bug in the week arithmetic. `planTargets` walks ET day
 * boundaries from `now` to the window end, ONE `ingest_targets` row per day per
 * league; a `boardWindowEnd` that returned a date years out would turn that loop
 * into thousands of statements inside a cron invocation with a 10 ms CPU budget.
 * The planner therefore clamps to `min(boardWindowEnd(...), now + this)`.
 */
export const INGEST_WINDOW_MS = 10 * 24 * 60 * 60 * 1000;

/* ------------------------------------------------------------------ *
 * The board / ingest window (PLAN.md §22)
 *
 * A football week runs TUESDAY through MONDAY, and the board ends on the Monday
 * that closes the current week, INCLUSIVE — Monday Night Football is a Monday ET
 * date. The product owner's rule: never show a game more than a week out,
 * because the lines move too much after the weekend to be worth betting into.
 *
 * The week advances at a fixed ET instant on Sunday, per league, because the two
 * leagues finish their slates at different times. Both are HOURS of the ET
 * calendar day (minutes are always :00), evaluated with the same
 * `Intl.DateTimeFormat`-based ET helpers as `etDateKey` — no hard-coded -4/-5,
 * so DST is handled by the tz database rather than by arithmetic.
 * ------------------------------------------------------------------ */

/**
 * CFB rolls over at Sunday 00:00 ET: Saturday's games are done the moment the ET
 * day ends, so the whole of Sunday already belongs to next week's board.
 */
export const NCAAF_WEEK_ROLLOVER_ET_HOUR = 0;

/**
 * The NFL rolls over at Sunday 20:00 ET, after the early and late windows have
 * finished. Sunday Night Football and this week's Monday nighter stay on the
 * board across the rollover anyway, because the window END is inclusive of
 * Monday and the new end is a week FURTHER out.
 */
export const NFL_WEEK_ROLLOVER_ET_HOUR = 20;

/** The two above, keyed by league. `boardWindowEnd` reads only this. */
export const WEEK_ROLLOVER_ET_HOUR: Readonly<Record<League, number>> = {
  nfl: NFL_WEEK_ROLLOVER_ET_HOUR,
  ncaaf: NCAAF_WEEK_ROLLOVER_ET_HOUR,
};

/**
 * A postponed game (or one that vanished from the feed) is auto-voided once this
 * long has passed since its ORIGINAL kickoff. See PLAN.md §7.5.
 */
export const VOID_AFTER_MS = 7 * 24 * 60 * 60 * 1000;

/** Session lifetime, and the minimum age before we bother rewriting the row. */
export const SESSION_TTL_MS = 30 * 24 * 60 * 60 * 1000;
export const SESSION_TOUCH_INTERVAL_MS = 24 * 60 * 60 * 1000;
export const SESSION_COOKIE_NAME = 'sbs_session';

/** Header every state-changing request must carry. See PLAN.md §10.5. */
export const CSRF_HEADER = 'X-SBS-Client';
export const CSRF_HEADER_VALUE = '1';

/** Login throttling. */
export const AUTH_WINDOW_MS = 15 * 60 * 1000;
export const AUTH_MAX_FAILURES = 10;
export const AUTH_LOCKOUT_MS = 15 * 60 * 1000;

/**
 * Password KDF parameters. The heavy stretching runs in the BROWSER because the
 * Workers free plan allows only 10 ms of CPU per invocation. See PLAN.md §10.
 *
 * `saltPrefix` + lowercased username is hashed to produce a deterministic client
 * salt, so there is no "fetch my salt" endpoint and therefore no user-enumeration
 * oracle.
 */
export const KDF_VERSION = 1;
export const CLIENT_KDF = {
  algorithm: 'PBKDF2',
  hash: 'SHA-256',
  iterations: 210_000,
  keyLengthBytes: 32,
  saltPrefix: 'SBS-v1|',
} as const;
export const SERVER_KDF_ITERATIONS = 1_000;
export const SERVER_SALT_BYTES = 16;

/** Username policy (enforced server-side; the DB also has a length CHECK). */
export const USERNAME_MIN = 3;
export const USERNAME_MAX = 24;
export const USERNAME_PATTERN = /^[a-z0-9_]+$/;

/** Advisory only — the server never sees the plaintext password. */
export const PASSWORD_MIN_LENGTH = 10;

/**
 * Settlement chunk bookkeeping. A bet that is selected as settleable but still
 * grades `pending` (all games final, but a score is unparseable) increments
 * `bets.settle_attempts`; past this it is de-prioritised and reported, so it can
 * never block the head of the queue. See PLAN.md §7.1.
 *
 * 96 attempts at the 15-minute settle cadence = **24 hours** of patience before a
 * bet is parked for a human. An earlier value of 5 gave up after 1.25 h, which is
 * well inside the window in which a transiently malformed ESPN score is
 * plausible — and there was no reset path, so a brief feed glitch could park a
 * bet permanently.
 *
 * There are now TWO ways out, so 96 is a ceiling rather than a death sentence:
 *   1. The settle job's first statement each run zeroes `settle_attempts` for any
 *      deferred bet whose leg games have been updated since `settle_attempted_at`
 *      — i.e. the moment ESPN publishes a sane score, the bet gets a fresh 24 h.
 *   2. `POST /api/admin/bets/:id/retry-settlement` clears it manually.
 */
export const MAX_SETTLE_ATTEMPTS = 96;

/** Job names. Must match the `job_locks` rows seeded by migration 0001. */
export const JOB_NAMES = ['refresh', 'settle', 'maintenance'] as const;

/** Lease TTLs, all shorter than their cron period so a crash self-heals. */
export const JOB_LEASE_TTL_MS: Readonly<Record<(typeof JOB_NAMES)[number], number>> = {
  refresh: 5 * 60 * 1000,
  settle: 5 * 60 * 1000,
  maintenance: 10 * 60 * 1000,
};

/** ESPN request tuning. */
export const ESPN_TIMEOUT_MS = 8_000;
export const ESPN_MAX_WARNINGS_RECORDED = 20;
export const ESPN_DRAFTKINGS_PROVIDER_ID = '100';

/** Sanity bounds for parsed market data; anything outside is dropped + warned. */
export const MAX_ABS_LINE_TENTHS = 1_000;
export const MIN_ABS_AMERICAN_PRICE = 100;
export const MAX_ABS_AMERICAN_PRICE = 100_000;

/** Board query defaults. */
export const BOARD_LOOKBACK_MS = 12 * 60 * 60 * 1000;
export const BOARD_MAX_GAMES = 300;

/**
 * FBS conferences by ESPN `team.conferenceId`, for the CFB board filter
 * (PLAN.md §12.1). Ids are as ESPN reports them, confirmed against
 * docs/samples/espn-cfb-scoreboard.json (the 17 Big Ten teams sit under 5, the
 * 16 SEC teams under 8, and so on). ESPN occasionally files an FCS opponent
 * under an FBS id (the sample has North Dakota State under 17 and Sacramento
 * State under 15), so the filter's "Other" bucket — any id not in this list —
 * is best-effort, not a guarantee of FCS. Order is display order.
 */
export const CFB_CONFERENCES: readonly { readonly id: string; readonly name: string }[] = [
  { id: '8', name: 'SEC' },
  { id: '5', name: 'Big Ten' },
  { id: '4', name: 'Big 12' },
  { id: '1', name: 'ACC' },
  { id: '18', name: 'Independents' },
  { id: '151', name: 'American' },
  { id: '17', name: 'Mountain West' },
  { id: '37', name: 'Sun Belt' },
  { id: '15', name: 'MAC' },
  { id: '12', name: 'Conference USA' },
  { id: '9', name: 'Pac-12' },
];

/**
 * Bug reports (PLAN.md §11.7). A report is stored in `bug_reports` and filed as
 * a GitHub issue. The limits bound what one signed-in user can push into the
 * issue tracker: a title, a description, the page they were on, and at most
 * `BUG_REPORTS_PER_WINDOW` reports per `BUG_REPORT_WINDOW_MS`.
 */
export const BUG_REPORT_TITLE_MIN = 3;
export const BUG_REPORT_TITLE_MAX = 120;
export const BUG_REPORT_DESCRIPTION_MIN = 10;
export const BUG_REPORT_DESCRIPTION_MAX = 4_000;
export const BUG_REPORT_PAGE_MAX = 200;
/** The request's User-Agent is stored and filed too; anything past this is cut. */
export const BUG_REPORT_USER_AGENT_MAX = 300;
/**
 * The browser's diagnostics log (recent errors, API calls, routes — see
 * src/web/lib/diagnostics.ts) rides along with a report. The client renders it
 * to fit; the server refuses anything longer.
 */
export const BUG_REPORT_DIAGNOSTICS_MAX = 8_000;
/** The uncaught-error beacon (`POST /api/bugs/client-errors`) carries at most this. */
export const CLIENT_ERROR_BEACON_MAX = 2_000;
export const BUG_REPORTS_PER_WINDOW = 5;
export const BUG_REPORT_WINDOW_MS = 60 * 60 * 1000;

/* ------------------------------------------------------------------ *
 * Secondary odds provider — The Odds API v4 (PLAN.md §21)
 *
 * The PRIMARY feed stays DraftKings-via-ESPN. The secondary fills, PER MARKET,
 * only what the primary is missing, and only for games worth the credit: every
 * NFL game and any CFB game with a top-25 team. It rides the existing `refresh`
 * cron — no fourth trigger — and is OFF entirely when `ODDS_API_KEY` is unset.
 * ------------------------------------------------------------------ */

/** `game_lines.provider` of the ESPN/DraftKings row. The PRIMARY. */
export const LINE_PROVIDER_PRIMARY = 'DraftKings';

/**
 * `game_lines.provider` of the ONE secondary row per game. Deliberately a
 * constant rather than a per-bookmaker string: the PK is `(game_id, provider)`,
 * so a fixed provider makes "two secondary rows for one game with different
 * `seen_at`" impossible by construction, and makes a WITHDRAWAL a plain NULL in
 * the next upsert instead of an orphan row nobody deletes. Which book each
 * market came from is carried by `game_lines.spread_book / total_book / ml_book`
 * (migration 0007), so the provenance is not lost. PLAN.md §21.3.
 */
export const LINE_PROVIDER_SECONDARY = 'odds-api';

/**
 * Provider preference for the per-market merge (`mergeEffectiveLine`, in
 * src/shared/lines.ts). Earlier wins outright when it has the market and is
 * fresh — so the moment the primary re-posts a market it takes the board back.
 * A provider not in this list sorts last, then by `seen_at DESC, provider ASC`,
 * which is the tie-break the board and placement already shared.
 */
export const LINE_PROVIDER_PRIORITY: readonly string[] = [
  LINE_PROVIDER_PRIMARY,
  LINE_PROVIDER_SECONDARY,
];

/**
 * Bookmaker preference WITHIN one Odds API response, and simultaneously the
 * `bookmakers=` request parameter. A whole market (line AND both prices) is
 * always taken from ONE book — never a line from one and a price from another.
 *
 * Sent as `bookmakers=` rather than `regions=us` because the two cost the SAME
 * three credits (markets × regions, and a bookmaker list counts as one region)
 * while cutting the NCAAF payload from 320 KB to 197 KB — which matters for the
 * 10 ms Worker CPU budget, since this parse shares an invocation with the ESPN
 * ingest. PLAN.md §21.6.
 */
export const ODDS_API_BOOKMAKERS: readonly string[] = [
  'draftkings',
  'fanduel',
  'betmgm',
  'betrivers',
  'bovada',
];

/** The three markets we ask for; also the per-sweep credit cost (markets × 1 region). */
export const ODDS_API_MARKETS: readonly string[] = ['spreads', 'totals', 'h2h'];

/**
 * Credits one league sweep costs. MEASURED 2026-09-16 from `x-requests-last`:
 * `markets × regions` = 3 × 1. Keep it equal to `ODDS_API_MARKETS.length`; it is
 * a separate constant because the budget arithmetic reads it, not the array.
 */
export const ODDS_API_COST_PER_SWEEP = 3;

/** Free tier, reset by the provider on the 1st of each calendar month. */
export const ODDS_API_MONTHLY_CREDITS = 500;

/**
 * A sweep is refused when it would drop `x-requests-remaining` below this.
 *
 * It is a CUSHION FOR DEBIT DRIFT, nothing more, which is why it is 25 and not
 * the 100 an earlier draft carried. The claim debits `ODDS_API_COST_PER_SWEEP`
 * pessimistically BEFORE the request and the response header then overwrites the
 * balance with the truth; between two such corrections the stored number can
 * only ever be too LOW (a timed-out request may not have been counted by the
 * provider), never too high. The reserve covers that drift plus one in-flight
 * sweep: 25 is eight sweeps' worth.
 *
 * The number used to be 100 because the budget probe cost 3 credits and could
 * fire 31 times a month. It does not: `GET /v4/sports` is FREE — verified twice
 * against the live API on 2026-09-16, `x-requests-last: 0` with
 * `x-requests-used` / `x-requests-remaining` both present — so the probe spends
 * nothing and the reserve no longer has to out-size it (§21.5, spike S5).
 */
export const ODDS_API_CREDIT_RESERVE = 25;

/**
 * At most one FREE budget probe (`GET /v4/sports`) per this long while the
 * reserve is blocking sweeps.
 *
 * The probe exists because the provider's quota resets on ITS calendar, in a
 * timezone we are not told: without it, a month that hit the reserve would never
 * make another request, never see a fresh `x-requests-remaining`, and the feature
 * would stay off forever. A plain 24 h timer means we do no month arithmetic at
 * all and are immune to reset-boundary clock skew. Because the probe costs no
 * credits, the throttle is about request politeness and D1 writes, not budget.
 */
export const ODDS_API_BUDGET_PROBE_MS = 24 * 60 * 60 * 1000;

/**
 * Floor between two sweeps OF THE SAME LEAGUE, enforced in the `WHERE` of the
 * credit claim rather than in the decision logic. It is the blast radius limiter
 * for a decision bug: measured, a decision function stuck on "yes" drains to the
 * reserve in ONE day without it and in SEVEN with it. It never delays a
 * legitimate sweep, because the tightest legitimate cadence is 2 h 15 m (the
 * 3 h staleness window less `SECONDARY_RESWEEP_MARGIN_MS`).
 */
export const SECONDARY_MIN_SWEEP_INTERVAL_MS = 2 * 60 * 60 * 1000;

/**
 * A 429 or a transport failure parks the whole feature for this long — the FIRST
 * time. Consecutive failures double it (`secondary_budget.consecutive_failures`)
 * up to `ODDS_API_COOLDOWN_MAX_MS`, because a flat hour against a provider that
 * is down for a day costs 24 × 2 leagues × 3 = 144 credits to learn nothing.
 * A 2xx of any kind — including a free probe — resets the counter to 0.
 */
export const ODDS_API_COOLDOWN_MS = 60 * 60 * 1000;

/**
 * Ceiling on that doubling: 8 h, so a provider outage costs at most 3 sweeps ×
 * 2 leagues × 3 credits = 18 credits a day instead of 144, and a feed that comes
 * back is noticed within 8 h even if nobody looks. Not a credit guard (the free
 * probe corrects the debit anyway) — a politeness guard with a bounded recovery
 * time.
 */
export const ODDS_API_COOLDOWN_MAX_MS = 8 * 60 * 60 * 1000;

export const ODDS_API_TIMEOUT_MS = 8_000;

/**
 * A game the sweep could NOT fill is not attempted again for this long. Only
 * games that STILL lack a market after the sweep are stamped
 * (`games.secondary_tried_at`), so a filled game costs no write and needs no
 * backoff — it is no longer missing a market on the effective line.
 */
export const SECONDARY_RETRY_MS = 4 * 60 * 60 * 1000;

/**
 * A secondary market IN USE must be re-confirmed before it goes stale, or it
 * silently vanishes from the board mid-Saturday. The re-sweep deadline is
 * `seen_at + lineStaleAfterMs(kickoff, seen_at) − this`, so it inherits the SAME
 * window the board and placement use: 2 h 15 m for a game inside 48 h of
 * kickoff, 17 h 15 m for one further out.
 *
 * Deliberately a MARGIN and not a flat interval: a flat 2.5 h would re-sweep a
 * fill on a game five days out roughly seven times more often than its 18 h
 * window needs, and the credits are the scarce resource. 45 minutes is three
 * `refresh` cron ticks, so two consecutive missed or lease-skipped runs still
 * leave the fill fresh.
 */
export const SECONDARY_RESWEEP_MARGIN_MS = 45 * 60 * 1000;

/**
 * The fallback matcher's kickoff tolerance. ESPN and the Odds API agreed to the
 * minute on 106 of 107 captured events; the one exception was 30 minutes apart.
 * Used ONLY with both mascots equal AND exactly one candidate. PLAN.md §21.7.
 */
export const SECONDARY_MATCH_WINDOW_MS = 90 * 60 * 1000;
