/**
 * Vitest setup for the `worker` project.
 *
 * 1. Applies migrations/0001_init.sql to Miniflare's D1 via `applyD1Migrations`
 *    from `cloudflare:test`, so tests exercise the REAL schema — triggers, CHECK
 *    constraints and UNIQUE indexes included. That matters here more than usual,
 *    because the money invariants LIVE in the DDL (PLAN.md §4.1); a mock DB would
 *    not test them at all.
 * 2. Installs the `https://espn.test/**` fetch stub from ./fixtures.ts, so no
 *    test touches the network and ingestion is deterministic.
 *
 * CONSTRAINT — workerd caps PBKDF2 at 100,000 iterations and throws
 * `OperationError` above it. `CLIENT_KDF.iterations` is 210,000, which is a
 * BROWSER/Node number. Worker-project tests must therefore NEVER derive a `dk`
 * in-pool: use the hard-coded hex vectors exported below, which are generated by
 * (and pinned against) tests/unit/kdf-parity.spec.ts. The server-side KDF
 * (SERVER_KDF_ITERATIONS = 1,000) is far under the cap and runs normally.
 *
 * See Spike S3.
 */

export {};

// TODO(M1): beforeAll -> await applyD1Migrations(env.DB, env.TEST_MIGRATIONS)
// TODO(M1): stubEspn() from ./fixtures.ts; afterEach -> restore()
// TODO(M3): export const DK_VECTORS = { alex: '…64 hex…', bob: '…' } — PRECOMPUTED
//           in Node by scripts/admin-hash.mjs; never call deriveKey() in-pool.
// TODO(M1): seedUser() / seedGame() / seedLine() builders shared by the specs
