/**
 * Vitest setup for the `worker` project.
 *
 * 1. Applies migrations/0001_init.sql to Miniflare's D1 via `applyD1Migrations`
 *    from `cloudflare:test`, so tests exercise the REAL schema — triggers, CHECK
 *    constraints and UNIQUE indexes included. That matters here more than usual,
 *    because the money invariants LIVE in the DDL (PLAN.md §4.1); a mock DB would
 *    not test them at all.
 * 2. (M4) Installs the `https://espn.test/**` fetch stub from ./fixtures.ts, so
 *    no test touches the network and ingestion is deterministic.
 *
 * Isolation: vitest-pool-workers gives every test FILE a fresh copy of storage
 * and, with the default `isolatedStorage`, rolls back each test's writes. The
 * migration therefore runs once per file (beforeAll) and every test starts from
 * the seeded schema.
 *
 * CONSTRAINT — workerd caps PBKDF2 at 100,000 iterations and throws
 * `OperationError` above it. `CLIENT_KDF.iterations` is 210,000, which is a
 * BROWSER/Node number. Worker-project tests must therefore NEVER derive a `dk`
 * in-pool: use hard-coded hex vectors (M3: `DK_VECTORS`), generated by
 * scripts/admin-hash.mjs and pinned by tests/unit/kdf-parity.spec.ts. The
 * server-side KDF (SERVER_KDF_ITERATIONS = 1,000) is far under the cap.
 *
 * See Spike S3.
 */

import { applyD1Migrations } from 'cloudflare:test';
import { env } from 'cloudflare:workers';
import { beforeAll } from 'vitest';

beforeAll(async () => {
  await applyD1Migrations(env.DB, [...env.TEST_MIGRATIONS]);
});

// TODO(M3): export const DK_VECTORS = { alex: '…64 hex…', bob: '…' } — PRECOMPUTED
//           in Node by scripts/admin-hash.mjs; never call deriveKey() in-pool.
// TODO(M4): stubEspn() from ./fixtures.ts; afterEach -> restore()
