/**
 * Vitest setup for the `worker` project.
 *
 * 1. Applies migrations/0001_init.sql to Miniflare's D1 via `applyD1Migrations`
 *    from `cloudflare:test`, so tests exercise the REAL schema — triggers, CHECK
 *    constraints and UNIQUE indexes included. That matters here more than usual,
 *    because the money invariants LIVE in the DDL (PLAN.md §4.1); a mock DB would
 *    not test them at all.
 * 2. (M4) Installs the `https://espn.test/**` fetch stub from ./fixtures.ts, so
 *    no test touches the network and ingestion is deterministic.
 *
 * Isolation: vitest-pool-workers gives every test FILE a fresh copy of storage
 * and, with the default `isolatedStorage`, rolls back each test's writes. The
 * migration therefore runs once per file (beforeAll) and every test starts from
 * the seeded schema.
 *
 * CONSTRAINT — workerd caps PBKDF2 at 100,000 iterations and throws
 * `OperationError` above it. `CLIENT_KDF.iterations` is 210,000, which is a
 * BROWSER/Node number. Worker-project tests must therefore NEVER derive a `dk`
 * in-pool: use hard-coded hex vectors (M3: `DK_VECTORS`), generated by
 * scripts/admin-hash.mjs and pinned by tests/unit/kdf-parity.spec.ts. The
 * server-side KDF (SERVER_KDF_ITERATIONS = 1,000) is far under the cap.
 *
 * See Spike S3.
 */

import { applyD1Migrations } from 'cloudflare:test';
import { env } from 'cloudflare:workers';
import { beforeAll } from 'vitest';

beforeAll(async () => {
  await applyD1Migrations(env.DB, [...env.TEST_MIGRATIONS]);
});

/**
 * PRECOMPUTED browser-derived keys — the 64-hex `dk` a real browser would POST.
 *
 * DO NOT call `deriveKey()` (or any 210,000-iteration PBKDF2) inside the pool.
 * These are the ONLY dks the worker project may use.
 *
 * MEASURED CORRECTION (2026-09-13, workerd 1.20260911.1 @ compatibility_date
 * 2026-08-22): the "workerd caps PBKDF2 at 100,000 iterations and throws
 * OperationError above it" line in CLAUDE.md / PLAN.md §10.2 is STALE — a
 * 210,000-iteration deriveBits completes in-pool and returns the correct key.
 * The rule above stands anyway, on the constraint that actually binds: the
 * Workers FREE plan allows 10 ms of CPU per invocation, and a 210k PBKDF2 costs
 * 25-100 ms. A test that derived a dk in-pool would be exercising something the
 * deployed Worker can never do. The split KDF is unaffected.
 *
 * Generated with, one line per entry:
 *
 *     node scripts/admin-hash.mjs alex  correct-horse-battery-staple
 *     node scripts/admin-hash.mjs bob   bobs-very-long-password
 *     node scripts/admin-hash.mjs carol carols-reset-password-9
 *     node scripts/admin-hash.mjs dave  daves-long-password-11
 *
 * ...taking the `dk:` line of each. The SAME values are pinned in
 * tests/unit/kdf-parity.spec.ts against an independent WebCrypto reference
 * implementation, so the browser, the admin script and these vectors cannot
 * drift apart.
 *
 * The client salt is `SHA-256('SBS-v1|' + username)`, so a vector is only valid
 * for the username it is named after: sign `alex` up with `DK_VECTORS.alex`.
 */
export const DK_VECTORS = {
  alex: '18b3bfaa9da6d403de76795e3096767721acfeacdbbe0f0fc69e9d460ad8f346',
  bob: 'c9d3c7d22fc7fe8f6cfde0ae0019c80be141e27611e1a0817c1d16f15e834253',
  carol: 'f36aebc96da7999f209d7c52102da3f784338098f8764607e251febb2091a701',
  dave: '0fa83955ee57563cae104768538f2565edf08c95d798977a47c657d63dd03850',
} as const;

/**
 * A well-formed 64-hex key that is NOT any user's: `deriveKey('alex',
 * 'Correct-horse-battery-staple')` — the same password with one letter
 * capitalised. Use it for "wrong password" assertions so the failure is a real
 * KDF mismatch and not a malformed-input rejection.
 */
export const WRONG_DK = '10290684da42e23a6f56a63c1a2caba7cef40dd59be2f35303c6b3f43305bdd1';

/**
 * (M4) The `https://espn.test/**` fetch stub lives in ./fixtures.ts and is
 * installed PER SPEC FILE (`stubEspn()` in `beforeEach`, `restore()` in
 * `afterEach`) rather than globally here. Each file owns its own slates and can
 * mutate them mid-test — kick a game off, move a line, serve a 503 — which a
 * single shared installation could not express. Files that make no upstream
 * request are left with the real `fetch`, so a test that accidentally starts
 * talking to the network fails loudly instead of being quietly served a fixture.
 */
